server:
  shutdown: graceful
  port: 8081
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - kafka.yml
      - logging.yml
      - monitoring.yml

resilience4j:
  circuitbreaker:
    instances:
      pgCircuit:
        sliding-window-size: 10
        failure-rate-threshold: 50       # 실패율이 50% 넘으면 Open
        slow-call-rate-threshold: 50
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 2s # Open 상태 유지 시간
        permitted-number-of-calls-in-half-open-state: 2
        slow-call-duration-threshold: 2s
        record-exceptions:
          - feign.FeignException.InternalServerError
          - java.io.IOException
          - java.util.concurrent.TimeoutException
      productCircuit:
        sliding-window-size: 10
        failure-rate-threshold: 50       # 실패율이 50% 넘으면 Open
        slow-call-rate-threshold: 50
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 2s # Open 상태 유지 시간
        permitted-number-of-calls-in-half-open-state: 2
        slow-call-duration-threshold: 400ms
        record-exceptions:
          - java.lang.RuntimeException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.dao.DataAccessException
          - java.sql.SQLException
  retry:
    instances:
      pgRetry:
        max-attempts: 2
        wait-duration: 600ms
        retry-exceptions:
          - feign.FeignException.InternalServerError
          - feign.RetryableException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        fail-after-max-attempts: false

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

pg:
  api:
    url: localhost:8082

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false
